"""agregando is_online a modelo users

Revision ID: 94c897711b43
Revises: 10dfee02515f
Create Date: 2026-05-07 00:04:30.647227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94c897711b43'
down_revision: Union[str, Sequence[str], None] = '10dfee02515f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_users', sa.Column('is_online', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_users', 'is_online')
    # ### end Alembic commands ###
